defaults:
  - eval_pcgrl
  - _self_

  # - override hydra/launcher: submitit_local
  # - override hydra/launcher: submitit_slurm
  - override hydra/launcher: basic

hydra:
  verbose: true
  sweeper:
    params:
      # learning_rate: 1e-4, 1e-5, 5e-5

