defaults:
  - eval_pcgrl
  - _self_

  # - override hydra/launcher: drill_local
  # - override hydra/launcher: drill_slurm
  - override hydra/launcher: drill_basic

hydra:
  verbose: true
  sweeper:
    params:
      #exp_id: 0, 1, 2
      # learning_rate: 5e-5
      learning_rate: 5e-6

  launcher:
    tasks_per_node: 1

    #FIXME: Can't set this to 1 or 2 even when only asking from 1 ("0") worker from ray...
    cpus_per_task: 13

    gpus_per_node: 1
    timeout_min: 60 # 1 day of training
    mem_gb: 30

    # array_parallelism: 3

  job:
    chdir: False